package com.richardxu.merchant.domain;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private String categoryLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level1
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private Integer categoryLevel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level1_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private String categoryLevel1Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level2
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private Integer categoryLevel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level2_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private String categoryLevel2Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level3
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private Integer categoryLevel3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level3_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private String categoryLevel3Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level4
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private Integer categoryLevel4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level4_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private String categoryLevel4Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level5
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private Integer categoryLevel5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level5_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private String categoryLevel5Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.deleted
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.leaf_flag
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private String leafFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.pt
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    private String pt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param categoryId the value for category.category_id
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level
     *
     * @return the value of category.category_level
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getCategoryLevel() {
        return categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level
     *
     * @param categoryLevel the value for category.category_level
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel(String categoryLevel) {
        this.categoryLevel = categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level1
     *
     * @return the value of category.category_level1
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public Integer getCategoryLevel1() {
        return categoryLevel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level1
     *
     * @param categoryLevel1 the value for category.category_level1
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel1(Integer categoryLevel1) {
        this.categoryLevel1 = categoryLevel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level1_name
     *
     * @return the value of category.category_level1_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getCategoryLevel1Name() {
        return categoryLevel1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level1_name
     *
     * @param categoryLevel1Name the value for category.category_level1_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel1Name(String categoryLevel1Name) {
        this.categoryLevel1Name = categoryLevel1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level2
     *
     * @return the value of category.category_level2
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public Integer getCategoryLevel2() {
        return categoryLevel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level2
     *
     * @param categoryLevel2 the value for category.category_level2
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel2(Integer categoryLevel2) {
        this.categoryLevel2 = categoryLevel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level2_name
     *
     * @return the value of category.category_level2_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getCategoryLevel2Name() {
        return categoryLevel2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level2_name
     *
     * @param categoryLevel2Name the value for category.category_level2_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel2Name(String categoryLevel2Name) {
        this.categoryLevel2Name = categoryLevel2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level3
     *
     * @return the value of category.category_level3
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public Integer getCategoryLevel3() {
        return categoryLevel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level3
     *
     * @param categoryLevel3 the value for category.category_level3
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel3(Integer categoryLevel3) {
        this.categoryLevel3 = categoryLevel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level3_name
     *
     * @return the value of category.category_level3_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getCategoryLevel3Name() {
        return categoryLevel3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level3_name
     *
     * @param categoryLevel3Name the value for category.category_level3_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel3Name(String categoryLevel3Name) {
        this.categoryLevel3Name = categoryLevel3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level4
     *
     * @return the value of category.category_level4
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public Integer getCategoryLevel4() {
        return categoryLevel4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level4
     *
     * @param categoryLevel4 the value for category.category_level4
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel4(Integer categoryLevel4) {
        this.categoryLevel4 = categoryLevel4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level4_name
     *
     * @return the value of category.category_level4_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getCategoryLevel4Name() {
        return categoryLevel4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level4_name
     *
     * @param categoryLevel4Name the value for category.category_level4_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel4Name(String categoryLevel4Name) {
        this.categoryLevel4Name = categoryLevel4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level5
     *
     * @return the value of category.category_level5
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public Integer getCategoryLevel5() {
        return categoryLevel5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level5
     *
     * @param categoryLevel5 the value for category.category_level5
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel5(Integer categoryLevel5) {
        this.categoryLevel5 = categoryLevel5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level5_name
     *
     * @return the value of category.category_level5_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getCategoryLevel5Name() {
        return categoryLevel5Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level5_name
     *
     * @param categoryLevel5Name the value for category.category_level5_name
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setCategoryLevel5Name(String categoryLevel5Name) {
        this.categoryLevel5Name = categoryLevel5Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.deleted
     *
     * @return the value of category.deleted
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.deleted
     *
     * @param deleted the value for category.deleted
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.leaf_flag
     *
     * @return the value of category.leaf_flag
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getLeafFlag() {
        return leafFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.leaf_flag
     *
     * @param leafFlag the value for category.leaf_flag
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setLeafFlag(String leafFlag) {
        this.leafFlag = leafFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.pt
     *
     * @return the value of category.pt
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getPt() {
        return pt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.pt
     *
     * @param pt the value for category.pt
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setPt(String pt) {
        this.pt = pt;
    }
}