package com.richardxu.merchant.domain;

import java.util.ArrayList;
import java.util.List;

public class CategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public CategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Integer value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Integer value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Integer value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Integer value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Integer> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Integer> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelIsNull() {
            addCriterion("category_level is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelIsNotNull() {
            addCriterion("category_level is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelEqualTo(String value) {
            addCriterion("category_level =", value, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelNotEqualTo(String value) {
            addCriterion("category_level <>", value, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelGreaterThan(String value) {
            addCriterion("category_level >", value, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelGreaterThanOrEqualTo(String value) {
            addCriterion("category_level >=", value, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelLessThan(String value) {
            addCriterion("category_level <", value, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelLessThanOrEqualTo(String value) {
            addCriterion("category_level <=", value, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelLike(String value) {
            addCriterion("category_level like", value, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelNotLike(String value) {
            addCriterion("category_level not like", value, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelIn(List<String> values) {
            addCriterion("category_level in", values, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelNotIn(List<String> values) {
            addCriterion("category_level not in", values, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelBetween(String value1, String value2) {
            addCriterion("category_level between", value1, value2, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryLevelNotBetween(String value1, String value2) {
            addCriterion("category_level not between", value1, value2, "categoryLevel");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIsNull() {
            addCriterion("category_name is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIsNotNull() {
            addCriterion("category_name is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameEqualTo(String value) {
            addCriterion("category_name =", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotEqualTo(String value) {
            addCriterion("category_name <>", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameGreaterThan(String value) {
            addCriterion("category_name >", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("category_name >=", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLessThan(String value) {
            addCriterion("category_name <", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("category_name <=", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLike(String value) {
            addCriterion("category_name like", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotLike(String value) {
            addCriterion("category_name not like", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIn(List<String> values) {
            addCriterion("category_name in", values, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotIn(List<String> values) {
            addCriterion("category_name not in", values, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameBetween(String value1, String value2) {
            addCriterion("category_name between", value1, value2, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotBetween(String value1, String value2) {
            addCriterion("category_name not between", value1, value2, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1IsNull() {
            addCriterion("category_level1 is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1IsNotNull() {
            addCriterion("category_level1 is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1EqualTo(Integer value) {
            addCriterion("category_level1 =", value, "categoryLevel1");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NotEqualTo(Integer value) {
            addCriterion("category_level1 <>", value, "categoryLevel1");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1GreaterThan(Integer value) {
            addCriterion("category_level1 >", value, "categoryLevel1");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1GreaterThanOrEqualTo(Integer value) {
            addCriterion("category_level1 >=", value, "categoryLevel1");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1LessThan(Integer value) {
            addCriterion("category_level1 <", value, "categoryLevel1");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1LessThanOrEqualTo(Integer value) {
            addCriterion("category_level1 <=", value, "categoryLevel1");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1In(List<Integer> values) {
            addCriterion("category_level1 in", values, "categoryLevel1");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NotIn(List<Integer> values) {
            addCriterion("category_level1 not in", values, "categoryLevel1");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1Between(Integer value1, Integer value2) {
            addCriterion("category_level1 between", value1, value2, "categoryLevel1");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NotBetween(Integer value1, Integer value2) {
            addCriterion("category_level1 not between", value1, value2, "categoryLevel1");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameIsNull() {
            addCriterion("category_level1_name is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameIsNotNull() {
            addCriterion("category_level1_name is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameEqualTo(String value) {
            addCriterion("category_level1_name =", value, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameNotEqualTo(String value) {
            addCriterion("category_level1_name <>", value, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameGreaterThan(String value) {
            addCriterion("category_level1_name >", value, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameGreaterThanOrEqualTo(String value) {
            addCriterion("category_level1_name >=", value, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameLessThan(String value) {
            addCriterion("category_level1_name <", value, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameLessThanOrEqualTo(String value) {
            addCriterion("category_level1_name <=", value, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameLike(String value) {
            addCriterion("category_level1_name like", value, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameNotLike(String value) {
            addCriterion("category_level1_name not like", value, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameIn(List<String> values) {
            addCriterion("category_level1_name in", values, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameNotIn(List<String> values) {
            addCriterion("category_level1_name not in", values, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameBetween(String value1, String value2) {
            addCriterion("category_level1_name between", value1, value2, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel1NameNotBetween(String value1, String value2) {
            addCriterion("category_level1_name not between", value1, value2, "categoryLevel1Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2IsNull() {
            addCriterion("category_level2 is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2IsNotNull() {
            addCriterion("category_level2 is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2EqualTo(Integer value) {
            addCriterion("category_level2 =", value, "categoryLevel2");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NotEqualTo(Integer value) {
            addCriterion("category_level2 <>", value, "categoryLevel2");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2GreaterThan(Integer value) {
            addCriterion("category_level2 >", value, "categoryLevel2");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2GreaterThanOrEqualTo(Integer value) {
            addCriterion("category_level2 >=", value, "categoryLevel2");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2LessThan(Integer value) {
            addCriterion("category_level2 <", value, "categoryLevel2");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2LessThanOrEqualTo(Integer value) {
            addCriterion("category_level2 <=", value, "categoryLevel2");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2In(List<Integer> values) {
            addCriterion("category_level2 in", values, "categoryLevel2");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NotIn(List<Integer> values) {
            addCriterion("category_level2 not in", values, "categoryLevel2");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2Between(Integer value1, Integer value2) {
            addCriterion("category_level2 between", value1, value2, "categoryLevel2");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NotBetween(Integer value1, Integer value2) {
            addCriterion("category_level2 not between", value1, value2, "categoryLevel2");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameIsNull() {
            addCriterion("category_level2_name is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameIsNotNull() {
            addCriterion("category_level2_name is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameEqualTo(String value) {
            addCriterion("category_level2_name =", value, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameNotEqualTo(String value) {
            addCriterion("category_level2_name <>", value, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameGreaterThan(String value) {
            addCriterion("category_level2_name >", value, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameGreaterThanOrEqualTo(String value) {
            addCriterion("category_level2_name >=", value, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameLessThan(String value) {
            addCriterion("category_level2_name <", value, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameLessThanOrEqualTo(String value) {
            addCriterion("category_level2_name <=", value, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameLike(String value) {
            addCriterion("category_level2_name like", value, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameNotLike(String value) {
            addCriterion("category_level2_name not like", value, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameIn(List<String> values) {
            addCriterion("category_level2_name in", values, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameNotIn(List<String> values) {
            addCriterion("category_level2_name not in", values, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameBetween(String value1, String value2) {
            addCriterion("category_level2_name between", value1, value2, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel2NameNotBetween(String value1, String value2) {
            addCriterion("category_level2_name not between", value1, value2, "categoryLevel2Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3IsNull() {
            addCriterion("category_level3 is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3IsNotNull() {
            addCriterion("category_level3 is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3EqualTo(Integer value) {
            addCriterion("category_level3 =", value, "categoryLevel3");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NotEqualTo(Integer value) {
            addCriterion("category_level3 <>", value, "categoryLevel3");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3GreaterThan(Integer value) {
            addCriterion("category_level3 >", value, "categoryLevel3");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3GreaterThanOrEqualTo(Integer value) {
            addCriterion("category_level3 >=", value, "categoryLevel3");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3LessThan(Integer value) {
            addCriterion("category_level3 <", value, "categoryLevel3");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3LessThanOrEqualTo(Integer value) {
            addCriterion("category_level3 <=", value, "categoryLevel3");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3In(List<Integer> values) {
            addCriterion("category_level3 in", values, "categoryLevel3");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NotIn(List<Integer> values) {
            addCriterion("category_level3 not in", values, "categoryLevel3");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3Between(Integer value1, Integer value2) {
            addCriterion("category_level3 between", value1, value2, "categoryLevel3");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NotBetween(Integer value1, Integer value2) {
            addCriterion("category_level3 not between", value1, value2, "categoryLevel3");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameIsNull() {
            addCriterion("category_level3_name is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameIsNotNull() {
            addCriterion("category_level3_name is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameEqualTo(String value) {
            addCriterion("category_level3_name =", value, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameNotEqualTo(String value) {
            addCriterion("category_level3_name <>", value, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameGreaterThan(String value) {
            addCriterion("category_level3_name >", value, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameGreaterThanOrEqualTo(String value) {
            addCriterion("category_level3_name >=", value, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameLessThan(String value) {
            addCriterion("category_level3_name <", value, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameLessThanOrEqualTo(String value) {
            addCriterion("category_level3_name <=", value, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameLike(String value) {
            addCriterion("category_level3_name like", value, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameNotLike(String value) {
            addCriterion("category_level3_name not like", value, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameIn(List<String> values) {
            addCriterion("category_level3_name in", values, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameNotIn(List<String> values) {
            addCriterion("category_level3_name not in", values, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameBetween(String value1, String value2) {
            addCriterion("category_level3_name between", value1, value2, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel3NameNotBetween(String value1, String value2) {
            addCriterion("category_level3_name not between", value1, value2, "categoryLevel3Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4IsNull() {
            addCriterion("category_level4 is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4IsNotNull() {
            addCriterion("category_level4 is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4EqualTo(Integer value) {
            addCriterion("category_level4 =", value, "categoryLevel4");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NotEqualTo(Integer value) {
            addCriterion("category_level4 <>", value, "categoryLevel4");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4GreaterThan(Integer value) {
            addCriterion("category_level4 >", value, "categoryLevel4");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4GreaterThanOrEqualTo(Integer value) {
            addCriterion("category_level4 >=", value, "categoryLevel4");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4LessThan(Integer value) {
            addCriterion("category_level4 <", value, "categoryLevel4");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4LessThanOrEqualTo(Integer value) {
            addCriterion("category_level4 <=", value, "categoryLevel4");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4In(List<Integer> values) {
            addCriterion("category_level4 in", values, "categoryLevel4");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NotIn(List<Integer> values) {
            addCriterion("category_level4 not in", values, "categoryLevel4");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4Between(Integer value1, Integer value2) {
            addCriterion("category_level4 between", value1, value2, "categoryLevel4");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NotBetween(Integer value1, Integer value2) {
            addCriterion("category_level4 not between", value1, value2, "categoryLevel4");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameIsNull() {
            addCriterion("category_level4_name is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameIsNotNull() {
            addCriterion("category_level4_name is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameEqualTo(String value) {
            addCriterion("category_level4_name =", value, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameNotEqualTo(String value) {
            addCriterion("category_level4_name <>", value, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameGreaterThan(String value) {
            addCriterion("category_level4_name >", value, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameGreaterThanOrEqualTo(String value) {
            addCriterion("category_level4_name >=", value, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameLessThan(String value) {
            addCriterion("category_level4_name <", value, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameLessThanOrEqualTo(String value) {
            addCriterion("category_level4_name <=", value, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameLike(String value) {
            addCriterion("category_level4_name like", value, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameNotLike(String value) {
            addCriterion("category_level4_name not like", value, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameIn(List<String> values) {
            addCriterion("category_level4_name in", values, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameNotIn(List<String> values) {
            addCriterion("category_level4_name not in", values, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameBetween(String value1, String value2) {
            addCriterion("category_level4_name between", value1, value2, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel4NameNotBetween(String value1, String value2) {
            addCriterion("category_level4_name not between", value1, value2, "categoryLevel4Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5IsNull() {
            addCriterion("category_level5 is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5IsNotNull() {
            addCriterion("category_level5 is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5EqualTo(Integer value) {
            addCriterion("category_level5 =", value, "categoryLevel5");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NotEqualTo(Integer value) {
            addCriterion("category_level5 <>", value, "categoryLevel5");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5GreaterThan(Integer value) {
            addCriterion("category_level5 >", value, "categoryLevel5");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5GreaterThanOrEqualTo(Integer value) {
            addCriterion("category_level5 >=", value, "categoryLevel5");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5LessThan(Integer value) {
            addCriterion("category_level5 <", value, "categoryLevel5");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5LessThanOrEqualTo(Integer value) {
            addCriterion("category_level5 <=", value, "categoryLevel5");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5In(List<Integer> values) {
            addCriterion("category_level5 in", values, "categoryLevel5");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NotIn(List<Integer> values) {
            addCriterion("category_level5 not in", values, "categoryLevel5");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5Between(Integer value1, Integer value2) {
            addCriterion("category_level5 between", value1, value2, "categoryLevel5");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NotBetween(Integer value1, Integer value2) {
            addCriterion("category_level5 not between", value1, value2, "categoryLevel5");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameIsNull() {
            addCriterion("category_level5_name is null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameIsNotNull() {
            addCriterion("category_level5_name is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameEqualTo(String value) {
            addCriterion("category_level5_name =", value, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameNotEqualTo(String value) {
            addCriterion("category_level5_name <>", value, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameGreaterThan(String value) {
            addCriterion("category_level5_name >", value, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameGreaterThanOrEqualTo(String value) {
            addCriterion("category_level5_name >=", value, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameLessThan(String value) {
            addCriterion("category_level5_name <", value, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameLessThanOrEqualTo(String value) {
            addCriterion("category_level5_name <=", value, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameLike(String value) {
            addCriterion("category_level5_name like", value, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameNotLike(String value) {
            addCriterion("category_level5_name not like", value, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameIn(List<String> values) {
            addCriterion("category_level5_name in", values, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameNotIn(List<String> values) {
            addCriterion("category_level5_name not in", values, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameBetween(String value1, String value2) {
            addCriterion("category_level5_name between", value1, value2, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andCategoryLevel5NameNotBetween(String value1, String value2) {
            addCriterion("category_level5_name not between", value1, value2, "categoryLevel5Name");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(String value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(String value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(String value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(String value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(String value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLike(String value) {
            addCriterion("deleted like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotLike(String value) {
            addCriterion("deleted not like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<String> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<String> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(String value1, String value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(String value1, String value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andLeafFlagIsNull() {
            addCriterion("leaf_flag is null");
            return (Criteria) this;
        }

        public Criteria andLeafFlagIsNotNull() {
            addCriterion("leaf_flag is not null");
            return (Criteria) this;
        }

        public Criteria andLeafFlagEqualTo(String value) {
            addCriterion("leaf_flag =", value, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagNotEqualTo(String value) {
            addCriterion("leaf_flag <>", value, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagGreaterThan(String value) {
            addCriterion("leaf_flag >", value, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagGreaterThanOrEqualTo(String value) {
            addCriterion("leaf_flag >=", value, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagLessThan(String value) {
            addCriterion("leaf_flag <", value, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagLessThanOrEqualTo(String value) {
            addCriterion("leaf_flag <=", value, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagLike(String value) {
            addCriterion("leaf_flag like", value, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagNotLike(String value) {
            addCriterion("leaf_flag not like", value, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagIn(List<String> values) {
            addCriterion("leaf_flag in", values, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagNotIn(List<String> values) {
            addCriterion("leaf_flag not in", values, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagBetween(String value1, String value2) {
            addCriterion("leaf_flag between", value1, value2, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andLeafFlagNotBetween(String value1, String value2) {
            addCriterion("leaf_flag not between", value1, value2, "leafFlag");
            return (Criteria) this;
        }

        public Criteria andPtIsNull() {
            addCriterion("pt is null");
            return (Criteria) this;
        }

        public Criteria andPtIsNotNull() {
            addCriterion("pt is not null");
            return (Criteria) this;
        }

        public Criteria andPtEqualTo(String value) {
            addCriterion("pt =", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtNotEqualTo(String value) {
            addCriterion("pt <>", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtGreaterThan(String value) {
            addCriterion("pt >", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtGreaterThanOrEqualTo(String value) {
            addCriterion("pt >=", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtLessThan(String value) {
            addCriterion("pt <", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtLessThanOrEqualTo(String value) {
            addCriterion("pt <=", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtLike(String value) {
            addCriterion("pt like", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtNotLike(String value) {
            addCriterion("pt not like", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtIn(List<String> values) {
            addCriterion("pt in", values, "pt");
            return (Criteria) this;
        }

        public Criteria andPtNotIn(List<String> values) {
            addCriterion("pt not in", values, "pt");
            return (Criteria) this;
        }

        public Criteria andPtBetween(String value1, String value2) {
            addCriterion("pt between", value1, value2, "pt");
            return (Criteria) this;
        }

        public Criteria andPtNotBetween(String value1, String value2) {
            addCriterion("pt not between", value1, value2, "pt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table category
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 04 16:36:38 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table category
     *
     * @mbggenerated Tue Jun 04 16:36:38 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}