package com.richardxu.merchant.domain;

import java.util.ArrayList;
import java.util.List;

public class MerchantExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public MerchantExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andIdcardIsNull() {
            addCriterion("idcard is null");
            return (Criteria) this;
        }

        public Criteria andIdcardIsNotNull() {
            addCriterion("idcard is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardEqualTo(String value) {
            addCriterion("idcard =", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotEqualTo(String value) {
            addCriterion("idcard <>", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardGreaterThan(String value) {
            addCriterion("idcard >", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("idcard >=", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLessThan(String value) {
            addCriterion("idcard <", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLessThanOrEqualTo(String value) {
            addCriterion("idcard <=", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLike(String value) {
            addCriterion("idcard like", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotLike(String value) {
            addCriterion("idcard not like", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardIn(List<String> values) {
            addCriterion("idcard in", values, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotIn(List<String> values) {
            addCriterion("idcard not in", values, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardBetween(String value1, String value2) {
            addCriterion("idcard between", value1, value2, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotBetween(String value1, String value2) {
            addCriterion("idcard not between", value1, value2, "idcard");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyIsNull() {
            addCriterion("other_property is null");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyIsNotNull() {
            addCriterion("other_property is not null");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyEqualTo(String value) {
            addCriterion("other_property =", value, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyNotEqualTo(String value) {
            addCriterion("other_property <>", value, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyGreaterThan(String value) {
            addCriterion("other_property >", value, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyGreaterThanOrEqualTo(String value) {
            addCriterion("other_property >=", value, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyLessThan(String value) {
            addCriterion("other_property <", value, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyLessThanOrEqualTo(String value) {
            addCriterion("other_property <=", value, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyLike(String value) {
            addCriterion("other_property like", value, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyNotLike(String value) {
            addCriterion("other_property not like", value, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyIn(List<String> values) {
            addCriterion("other_property in", values, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyNotIn(List<String> values) {
            addCriterion("other_property not in", values, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyBetween(String value1, String value2) {
            addCriterion("other_property between", value1, value2, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andOtherPropertyNotBetween(String value1, String value2) {
            addCriterion("other_property not between", value1, value2, "otherProperty");
            return (Criteria) this;
        }

        public Criteria andCellphoneIsNull() {
            addCriterion("cellphone is null");
            return (Criteria) this;
        }

        public Criteria andCellphoneIsNotNull() {
            addCriterion("cellphone is not null");
            return (Criteria) this;
        }

        public Criteria andCellphoneEqualTo(String value) {
            addCriterion("cellphone =", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneNotEqualTo(String value) {
            addCriterion("cellphone <>", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneGreaterThan(String value) {
            addCriterion("cellphone >", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneGreaterThanOrEqualTo(String value) {
            addCriterion("cellphone >=", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneLessThan(String value) {
            addCriterion("cellphone <", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneLessThanOrEqualTo(String value) {
            addCriterion("cellphone <=", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneLike(String value) {
            addCriterion("cellphone like", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneNotLike(String value) {
            addCriterion("cellphone not like", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneIn(List<String> values) {
            addCriterion("cellphone in", values, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneNotIn(List<String> values) {
            addCriterion("cellphone not in", values, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneBetween(String value1, String value2) {
            addCriterion("cellphone between", value1, value2, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneNotBetween(String value1, String value2) {
            addCriterion("cellphone not between", value1, value2, "cellphone");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditIsNull() {
            addCriterion("buyer_credit is null");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditIsNotNull() {
            addCriterion("buyer_credit is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditEqualTo(Integer value) {
            addCriterion("buyer_credit =", value, "buyerCredit");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditNotEqualTo(Integer value) {
            addCriterion("buyer_credit <>", value, "buyerCredit");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditGreaterThan(Integer value) {
            addCriterion("buyer_credit >", value, "buyerCredit");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyer_credit >=", value, "buyerCredit");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditLessThan(Integer value) {
            addCriterion("buyer_credit <", value, "buyerCredit");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditLessThanOrEqualTo(Integer value) {
            addCriterion("buyer_credit <=", value, "buyerCredit");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditIn(List<Integer> values) {
            addCriterion("buyer_credit in", values, "buyerCredit");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditNotIn(List<Integer> values) {
            addCriterion("buyer_credit not in", values, "buyerCredit");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditBetween(Integer value1, Integer value2) {
            addCriterion("buyer_credit between", value1, value2, "buyerCredit");
            return (Criteria) this;
        }

        public Criteria andBuyerCreditNotBetween(Integer value1, Integer value2) {
            addCriterion("buyer_credit not between", value1, value2, "buyerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerCreditIsNull() {
            addCriterion("seller_credit is null");
            return (Criteria) this;
        }

        public Criteria andSellerCreditIsNotNull() {
            addCriterion("seller_credit is not null");
            return (Criteria) this;
        }

        public Criteria andSellerCreditEqualTo(Integer value) {
            addCriterion("seller_credit =", value, "sellerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerCreditNotEqualTo(Integer value) {
            addCriterion("seller_credit <>", value, "sellerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerCreditGreaterThan(Integer value) {
            addCriterion("seller_credit >", value, "sellerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerCreditGreaterThanOrEqualTo(Integer value) {
            addCriterion("seller_credit >=", value, "sellerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerCreditLessThan(Integer value) {
            addCriterion("seller_credit <", value, "sellerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerCreditLessThanOrEqualTo(Integer value) {
            addCriterion("seller_credit <=", value, "sellerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerCreditIn(List<Integer> values) {
            addCriterion("seller_credit in", values, "sellerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerCreditNotIn(List<Integer> values) {
            addCriterion("seller_credit not in", values, "sellerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerCreditBetween(Integer value1, Integer value2) {
            addCriterion("seller_credit between", value1, value2, "sellerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerCreditNotBetween(Integer value1, Integer value2) {
            addCriterion("seller_credit not between", value1, value2, "sellerCredit");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelIsNull() {
            addCriterion("seller_vip_level is null");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelIsNotNull() {
            addCriterion("seller_vip_level is not null");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelEqualTo(Integer value) {
            addCriterion("seller_vip_level =", value, "sellerVipLevel");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelNotEqualTo(Integer value) {
            addCriterion("seller_vip_level <>", value, "sellerVipLevel");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelGreaterThan(Integer value) {
            addCriterion("seller_vip_level >", value, "sellerVipLevel");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("seller_vip_level >=", value, "sellerVipLevel");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelLessThan(Integer value) {
            addCriterion("seller_vip_level <", value, "sellerVipLevel");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelLessThanOrEqualTo(Integer value) {
            addCriterion("seller_vip_level <=", value, "sellerVipLevel");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelIn(List<Integer> values) {
            addCriterion("seller_vip_level in", values, "sellerVipLevel");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelNotIn(List<Integer> values) {
            addCriterion("seller_vip_level not in", values, "sellerVipLevel");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelBetween(Integer value1, Integer value2) {
            addCriterion("seller_vip_level between", value1, value2, "sellerVipLevel");
            return (Criteria) this;
        }

        public Criteria andSellerVipLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("seller_vip_level not between", value1, value2, "sellerVipLevel");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelIsNull() {
            addCriterion("buyer_vip_level is null");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelIsNotNull() {
            addCriterion("buyer_vip_level is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelEqualTo(Integer value) {
            addCriterion("buyer_vip_level =", value, "buyerVipLevel");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelNotEqualTo(Integer value) {
            addCriterion("buyer_vip_level <>", value, "buyerVipLevel");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelGreaterThan(Integer value) {
            addCriterion("buyer_vip_level >", value, "buyerVipLevel");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyer_vip_level >=", value, "buyerVipLevel");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelLessThan(Integer value) {
            addCriterion("buyer_vip_level <", value, "buyerVipLevel");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelLessThanOrEqualTo(Integer value) {
            addCriterion("buyer_vip_level <=", value, "buyerVipLevel");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelIn(List<Integer> values) {
            addCriterion("buyer_vip_level in", values, "buyerVipLevel");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelNotIn(List<Integer> values) {
            addCriterion("buyer_vip_level not in", values, "buyerVipLevel");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelBetween(Integer value1, Integer value2) {
            addCriterion("buyer_vip_level between", value1, value2, "buyerVipLevel");
            return (Criteria) this;
        }

        public Criteria andBuyerVipLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("buyer_vip_level not between", value1, value2, "buyerVipLevel");
            return (Criteria) this;
        }

        public Criteria andRegisterCidIsNull() {
            addCriterion("register_cid is null");
            return (Criteria) this;
        }

        public Criteria andRegisterCidIsNotNull() {
            addCriterion("register_cid is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterCidEqualTo(Integer value) {
            addCriterion("register_cid =", value, "registerCid");
            return (Criteria) this;
        }

        public Criteria andRegisterCidNotEqualTo(Integer value) {
            addCriterion("register_cid <>", value, "registerCid");
            return (Criteria) this;
        }

        public Criteria andRegisterCidGreaterThan(Integer value) {
            addCriterion("register_cid >", value, "registerCid");
            return (Criteria) this;
        }

        public Criteria andRegisterCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("register_cid >=", value, "registerCid");
            return (Criteria) this;
        }

        public Criteria andRegisterCidLessThan(Integer value) {
            addCriterion("register_cid <", value, "registerCid");
            return (Criteria) this;
        }

        public Criteria andRegisterCidLessThanOrEqualTo(Integer value) {
            addCriterion("register_cid <=", value, "registerCid");
            return (Criteria) this;
        }

        public Criteria andRegisterCidIn(List<Integer> values) {
            addCriterion("register_cid in", values, "registerCid");
            return (Criteria) this;
        }

        public Criteria andRegisterCidNotIn(List<Integer> values) {
            addCriterion("register_cid not in", values, "registerCid");
            return (Criteria) this;
        }

        public Criteria andRegisterCidBetween(Integer value1, Integer value2) {
            addCriterion("register_cid between", value1, value2, "registerCid");
            return (Criteria) this;
        }

        public Criteria andRegisterCidNotBetween(Integer value1, Integer value2) {
            addCriterion("register_cid not between", value1, value2, "registerCid");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shop_name in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shop_name not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyIsNull() {
            addCriterion("seller_b_c_property is null");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyIsNotNull() {
            addCriterion("seller_b_c_property is not null");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyEqualTo(String value) {
            addCriterion("seller_b_c_property =", value, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyNotEqualTo(String value) {
            addCriterion("seller_b_c_property <>", value, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyGreaterThan(String value) {
            addCriterion("seller_b_c_property >", value, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyGreaterThanOrEqualTo(String value) {
            addCriterion("seller_b_c_property >=", value, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyLessThan(String value) {
            addCriterion("seller_b_c_property <", value, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyLessThanOrEqualTo(String value) {
            addCriterion("seller_b_c_property <=", value, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyLike(String value) {
            addCriterion("seller_b_c_property like", value, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyNotLike(String value) {
            addCriterion("seller_b_c_property not like", value, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyIn(List<String> values) {
            addCriterion("seller_b_c_property in", values, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyNotIn(List<String> values) {
            addCriterion("seller_b_c_property not in", values, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyBetween(String value1, String value2) {
            addCriterion("seller_b_c_property between", value1, value2, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andSellerBCPropertyNotBetween(String value1, String value2) {
            addCriterion("seller_b_c_property not between", value1, value2, "sellerBCProperty");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidIsNull() {
            addCriterion("core_business_cid is null");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidIsNotNull() {
            addCriterion("core_business_cid is not null");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidEqualTo(Integer value) {
            addCriterion("core_business_cid =", value, "coreBusinessCid");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidNotEqualTo(Integer value) {
            addCriterion("core_business_cid <>", value, "coreBusinessCid");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidGreaterThan(Integer value) {
            addCriterion("core_business_cid >", value, "coreBusinessCid");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("core_business_cid >=", value, "coreBusinessCid");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidLessThan(Integer value) {
            addCriterion("core_business_cid <", value, "coreBusinessCid");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidLessThanOrEqualTo(Integer value) {
            addCriterion("core_business_cid <=", value, "coreBusinessCid");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidIn(List<Integer> values) {
            addCriterion("core_business_cid in", values, "coreBusinessCid");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidNotIn(List<Integer> values) {
            addCriterion("core_business_cid not in", values, "coreBusinessCid");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidBetween(Integer value1, Integer value2) {
            addCriterion("core_business_cid between", value1, value2, "coreBusinessCid");
            return (Criteria) this;
        }

        public Criteria andCoreBusinessCidNotBetween(Integer value1, Integer value2) {
            addCriterion("core_business_cid not between", value1, value2, "coreBusinessCid");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Byte value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Byte value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Byte value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Byte value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Byte value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Byte value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Byte> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Byte> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Byte value1, Byte value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Byte value1, Byte value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andBirthIsNull() {
            addCriterion("birth is null");
            return (Criteria) this;
        }

        public Criteria andBirthIsNotNull() {
            addCriterion("birth is not null");
            return (Criteria) this;
        }

        public Criteria andBirthEqualTo(String value) {
            addCriterion("birth =", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthNotEqualTo(String value) {
            addCriterion("birth <>", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthGreaterThan(String value) {
            addCriterion("birth >", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthGreaterThanOrEqualTo(String value) {
            addCriterion("birth >=", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthLessThan(String value) {
            addCriterion("birth <", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthLessThanOrEqualTo(String value) {
            addCriterion("birth <=", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthLike(String value) {
            addCriterion("birth like", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthNotLike(String value) {
            addCriterion("birth not like", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthIn(List<String> values) {
            addCriterion("birth in", values, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthNotIn(List<String> values) {
            addCriterion("birth not in", values, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthBetween(String value1, String value2) {
            addCriterion("birth between", value1, value2, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthNotBetween(String value1, String value2) {
            addCriterion("birth not between", value1, value2, "birth");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchant
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 04 10:39:15 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchant
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
        
    }
}