package com.richardxu.merchant.domain;

public class Merchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.id
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.nickname
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.city
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.province
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.phone
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.email
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.idcard
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.other_property
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String otherProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.cellphone
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.buyer_credit
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private Integer buyerCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.seller_credit
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private Integer sellerCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.seller_vip_level
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private Integer sellerVipLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.buyer_vip_level
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private Integer buyerVipLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.register_cid
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private Integer registerCid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.shop_name
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.seller_b_c_property
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String sellerBCProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.core_business_cid
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private Integer coreBusinessCid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.gender
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.birth
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    private String birth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.id
     *
     * @return the value of merchant.id
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.id
     *
     * @param id the value for merchant.id
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.nickname
     *
     * @return the value of merchant.nickname
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.nickname
     *
     * @param nickname the value for merchant.nickname
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.city
     *
     * @return the value of merchant.city
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.city
     *
     * @param city the value for merchant.city
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.province
     *
     * @return the value of merchant.province
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.province
     *
     * @param province the value for merchant.province
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.phone
     *
     * @return the value of merchant.phone
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.phone
     *
     * @param phone the value for merchant.phone
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.email
     *
     * @return the value of merchant.email
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.email
     *
     * @param email the value for merchant.email
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.idcard
     *
     * @return the value of merchant.idcard
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.idcard
     *
     * @param idcard the value for merchant.idcard
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.other_property
     *
     * @return the value of merchant.other_property
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getOtherProperty() {
        return otherProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.other_property
     *
     * @param otherProperty the value for merchant.other_property
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setOtherProperty(String otherProperty) {
        this.otherProperty = otherProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.cellphone
     *
     * @return the value of merchant.cellphone
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.cellphone
     *
     * @param cellphone the value for merchant.cellphone
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.buyer_credit
     *
     * @return the value of merchant.buyer_credit
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public Integer getBuyerCredit() {
        return buyerCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.buyer_credit
     *
     * @param buyerCredit the value for merchant.buyer_credit
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setBuyerCredit(Integer buyerCredit) {
        this.buyerCredit = buyerCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.seller_credit
     *
     * @return the value of merchant.seller_credit
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public Integer getSellerCredit() {
        return sellerCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.seller_credit
     *
     * @param sellerCredit the value for merchant.seller_credit
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setSellerCredit(Integer sellerCredit) {
        this.sellerCredit = sellerCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.seller_vip_level
     *
     * @return the value of merchant.seller_vip_level
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public Integer getSellerVipLevel() {
        return sellerVipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.seller_vip_level
     *
     * @param sellerVipLevel the value for merchant.seller_vip_level
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setSellerVipLevel(Integer sellerVipLevel) {
        this.sellerVipLevel = sellerVipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.buyer_vip_level
     *
     * @return the value of merchant.buyer_vip_level
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public Integer getBuyerVipLevel() {
        return buyerVipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.buyer_vip_level
     *
     * @param buyerVipLevel the value for merchant.buyer_vip_level
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setBuyerVipLevel(Integer buyerVipLevel) {
        this.buyerVipLevel = buyerVipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.register_cid
     *
     * @return the value of merchant.register_cid
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public Integer getRegisterCid() {
        return registerCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.register_cid
     *
     * @param registerCid the value for merchant.register_cid
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setRegisterCid(Integer registerCid) {
        this.registerCid = registerCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.shop_name
     *
     * @return the value of merchant.shop_name
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.shop_name
     *
     * @param shopName the value for merchant.shop_name
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.seller_b_c_property
     *
     * @return the value of merchant.seller_b_c_property
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getSellerBCProperty() {
        return sellerBCProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.seller_b_c_property
     *
     * @param sellerBCProperty the value for merchant.seller_b_c_property
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setSellerBCProperty(String sellerBCProperty) {
        this.sellerBCProperty = sellerBCProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.core_business_cid
     *
     * @return the value of merchant.core_business_cid
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public Integer getCoreBusinessCid() {
        return coreBusinessCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.core_business_cid
     *
     * @param coreBusinessCid the value for merchant.core_business_cid
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setCoreBusinessCid(Integer coreBusinessCid) {
        this.coreBusinessCid = coreBusinessCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.gender
     *
     * @return the value of merchant.gender
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.gender
     *
     * @param gender the value for merchant.gender
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.birth
     *
     * @return the value of merchant.birth
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.birth
     *
     * @param birth the value for merchant.birth
     *
     * @mbggenerated Tue Jun 04 10:39:15 CST 2013
     */
    public void setBirth(String birth) {
        this.birth = birth;
    }
}