package com.richardxu.merchant.domain;

public class VipLevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_level.id
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_level.star_name
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    private String starName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_level.id
     *
     * @return the value of vip_level.id
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_level.id
     *
     * @param id the value for vip_level.id
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_level.star_name
     *
     * @return the value of vip_level.star_name
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    public String getStarName() {
        return starName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_level.star_name
     *
     * @param starName the value for vip_level.star_name
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    public void setStarName(String starName) {
        this.starName = starName;
    }
}