package com.richardxu.merchant.dao;

import com.richardxu.merchant.domain.VipLevel;
import com.richardxu.merchant.domain.VipLevelExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VipLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    int countByExample(VipLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    int deleteByExample(VipLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    int insert(VipLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    int insertSelective(VipLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    List<VipLevel> selectByExample(VipLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    VipLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    int updateByExampleSelective(@Param("record") VipLevel record, @Param("example") VipLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    int updateByExample(@Param("record") VipLevel record, @Param("example") VipLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    int updateByPrimaryKeySelective(VipLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_level
     *
     * @mbggenerated Sat Jun 08 14:30:23 CST 2013
     */
    int updateByPrimaryKey(VipLevel record);
}